export const metadataSEO = {
  title: "Dream Legal",
  description:
    "Solusi layanan hukum terpercaya di Indonesia. Konsultasi dengan konsultan hukum berpengalaman untuk pendirian PT, perizinan usaha, dan hak kekayaan intelektual.",
  openGraph: {
    title: "Dream Legal",
    description:
      "Solusi layanan hukum terpercaya di Indonesia. Konsultasi dengan konsultan hukum berpengalaman untuk pendirian PT, perizinan usaha, dan hak kekayaan intelektual.",
    images: [
      {
        url: "/img/Png 2.png",
        alt: "Dream Legal - Layanan Hukum Terpercaya",
      },
    ],
  },
  keywords: [
    "legal",
    "dreamlegal",
    "dream legal",
    "dream legal indonesia",
    "legal consultant",
    "layanan hukum",
    "layanan hukum online",
    "jasa hukum indonesia",
    "konsultasi hukum online",
    "pengacara profesional",
    "pendirian PT",
    "perizinan usaha",
    "konsultan hukum bisnis",
    "bantuan hukum perusahaan",
    "legal consultant jakarta",
    "pembuatan kontrak bisnis",
    "penyelesaian sengketa hukum",
    "legal service indonesia",
    "jasa notaris",
    "pendaftaran merek dagang",
    "izin usaha resmi",
    "konsultasi hukum bisnis",
    "haki",
    "merek",
    "daftar merek",
    "cara mendirikan PT",
    "biaya pendirian PT",
    "jasa pembuatan PT",
    "konsultan perizinan",
    "pembuatan CV",
    "pendaftaran hak cipta",
    "pendaftaran paten",
    "konsultan haki indonesia",
    "jasa pengurusan nib",
    "pembuatan akta notaris",
    "pengurusan izin usaha",
    "konsultasi hukum gratis",
    "pengacara jakarta",
    "firma hukum indonesia",
    "jasa pendirian perusahaan",
    "konsultan pajak",
    "pengurusan dokumen legal",
    "pembuatan perjanjian kerja",
    "pengurusan izin operational",
    "jasa virtual office",
    "pendirian yayasan",
    "pengurusan sertifikat halal",
    "pengurusan izin edar bpom",
    "konsultan hukum properti",
    "pengurusan sengketa dagang",
  ],
};
