import type { Metadata } from "next";
import { Libre_Baskerville, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Link from "next/link";
import Image from "next/image";

const LibreBaskerville = Libre_Baskerville({
  weight: "400",
  subsets: ['latin'],
  variable: "--font-display",
  display: "swap"
});

const PlusJakartaSans = Plus_Jakarta_Sans({
  weight: ['400', '600', '700', '800'],
  subsets: ['latin'],
  variable: "--font-body",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Dream Legal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreBaskerville.className} ${PlusJakartaSans.className} antialiased`}
      >
        <Link href="" className="fixed z-50 bottom-16 right-10 flex items-center gap-2 text-sm py-3 px-4 rounded-full bg-brand-green text-brand-dark-green font-bold shadow">
          <Image src="/img/WhatsApp-logo.png" alt="whatsapp-logo" width={21} height={21}/> Hubungi kami
        </Link>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
