import type { Metadata } from "next";
import { Libre_Baskerville, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const LibreBaskerville = Libre_Baskerville({
  weight: "400",
  subsets: ['latin'],
});

const PlusJakartaSans = Plus_Jakarta_Sans({
  weight: ['400', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Dream Legal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreBaskerville.className} ${PlusJakartaSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
